
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  selector:
    matchLabels:
      app: simulator
  replicas: 2
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: riteshcr.azurecr.io/simulator:v1
        
  
        ports:
        - containerPort: 8001

