name: build and deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    # environment: azure-new
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: 8b838f72-cc58-41f2-89c5-99bb78b50ad9
          tenant-id: 90dd04ee-72ca-46cd-8662-0d614e24d498
          subscription-id: 933094f8-3653-44a5-b6f6-04a0992bcf41

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group RG22 \
            --name KC100 \
            --overwrite-existing

      - name: Check AKS
        run: |
          kubectl config current-context
          kubectl get nodes

      - name: Deploy all manifests
        run: |
          kubectl apply -f ./manifest/
